### ISSUE TITLE
Problem with pc.validate(move, curSolution, curVal, data)

### ISSUE THREAD

**Issue by huanfachen** [hdbeukel/james-core#41] opened 2017-05-31 17:17 UTC
Possible bug:
Line 445 in GenericProblem.java
PenalizingValidation newVal = pc.validate(move, curSolution, curVal, data);

> The method validate(Move<? super SolutionType>, SolutionType, Validation, capture#96-of ? super DataType) is ambiguous for the type PenalizingConstraint<capture#95-of ? super SolutionType,capture#96-of ? super DataType>	GenericProblem.java	/james-core/src/main/java/org/jamesframework/core/problems	line 445	Java Problem

Environment:
Java 1.8.0_66 
Eclipse Mars.1 Release (4.5.1)
Windows 7 64-bit

**Comment by hdbeukel** [comment] 2017-06-01 07:39
Duplicate of #31. This is not a bug in JAMES but an issue with Eclipse. Maybe you can try the latest (dev) version of Eclipse, else use a different IDE.

**Closed as completed** 2017-06-01 07:39 UTC
