### ISSUE TITLE
Warning in code

### ISSUE THREAD

**Issue by neokito** [hdbeukel/james-core#31] opened 2016-03-18 15:21 UTC
Hi,

I have clone your repo james-core, but exists a warning in the file GenericProblem.java (version 1.2-SNAPSHOT)

Thanks :)

`The method validate(Move<? super SolutionType>, SolutionType, Validation, capture#96-of ? super DataType) is ambiguous for the type PenalizingConstraint<capture#95-of ? super SolutionType,capture#96-of ? super DataType>`

<img width="1110" alt="screen shot 2016-03-18 at 12 05 39" src="https://cloud.githubusercontent.com/assets/5897215/13882249/789830c8-ed03-11e5-82ea-5a499512ff40.png">

**Comment by hdbeukel** [comment] 2016-03-18 17:45
Hi,

I haven't seen this error before but will check.

Which java version are you using? Is there also a compile error when running `mvn install` from command line?

Edit: I double checked and don't get this warning/error. The latest snapshot builds fine. Did you make any changes to the code?

**Comment by neokito** [comment] 2016-03-21 15:34
Hi Hdbeukel

Attach mvn install output, 
What version of Eclipse you're using?
Cheers :)

> MacBook-Pro-2:james Salazar$ java -version
> java version "1.8.0_40"
> Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
> Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

And Eclipse Install configuration 
[Eclipse-install-configuration.txt](https://github.com/hdbeukel/james-core/files/182542/Eclipse-install-configuration.txt)

[james-maven.txt](https://github.com/hdbeukel/james-core/files/182540/james-maven.txt)

<img width="581" alt="screen shot 2016-03-21 at 12 34 24" src="https://cloud.githubusercontent.com/assets/5897215/13923729/9b1bfefe-ef60-11e5-9ac6-89ad2753c003.png">

**Comment by hdbeukel** [comment] 2016-03-21 15:48
I can see that JAMES builds fine when running `mvn install` from command line. So assuming that you did not make any changes it seems to be an Eclipse issue. I don't use Eclipse myself (NetBeans and IntelliJ IDEA) but will check with Eclipse.

**Comment by hdbeukel** [comment] 2016-03-22 13:02
I was able to reproduce the issue when opening the project in Eclipse. Strange, I have not seen this error in any other IDE nor when running Maven from command line. I guess Eclipse is wrong so I'll see if there is any solution. Else I recommend using a different IDE.

**Comment by neokito** [comment] 2016-03-22 13:21
Hi

I review with Netbeans 8.1 without error.... Is likely to be the version of Eclipse, I will be tested with other versions of Eclipse, yes Eclipse is wrong xD

<img width="1276" alt="screen shot 2016-03-22 at 10 23 06" src="https://cloud.githubusercontent.com/assets/5897215/13952835/84157c64-f017-11e5-89a9-0b5c68499416.png">

**Comment by hdbeukel** [comment] 2016-03-22 14:57
I tested with the latest development snapshot (Neon M5) and the issue still occurs. If this is ok for you I advise to use an other IDE like NetBeans or IntelliJ IDEA. I will close the issue since it is not a problem with JAMES but with Eclipse.

**Closed as completed by hdbeukel** 2016-03-22 14:57 UTC
